name: sms_forwarder
description: "An optimized Flutter project for SMS forwarding and QR scanning."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0" # دعم أحدث إصدار من Dart مع إبقاء التوافق

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  flutter_background_service: ^5.1.0
  telephony: ^0.2.0
  material_color_utilities: ^0.11.1  
  mobile_scanner: ^3.2.0
  http: ^1.2.0
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.0.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^9.0.0
  logger: ^1.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # تحديث قواعد التحليل البرمجي

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
